### ISSUE TITLE
Exception when attempting to update parameter title

### ISSUE THREAD

**Issue by jrossignol** [DMagic1/KSP_Contract_Window#16]
It worked the first try, but this happens when loading up a new save from the main menu where I have the "Duration" parameter (which has a count-down timer displayed that updates every second):

```
[WRN 22:55:33.452] [Contracts +] Something went wrong when attempting to assign a new Parameter Title: System.InvalidOperationException: Operation is not valid due to the current state of the object
  at System.Linq.Enumerable.First[parameterContainer] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.First[parameterContainer] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 
  at ContractsWindow.contractUtils.setParameterTitle (Contracts.Contract contract, Contracts.ContractParameter parameter, System.String name) [0x00000] in <filename unknown>:0 
```

**Comment by DMagic1** [comment]
I had a feeling this might be a problem. There are a few issues that I can think of. 

The exception is caused because I'm using First, so if nothing is found it doesn't have anything to check for null. I should probably change that to SingleOrDefault since there should never be two of the same parameter objects and the default return value would prevent the exception.

Another issue is that the contracts and their parameters aren't loaded by Contracts+ right away. It has to wait for the ContractSystem scenario module to load first, which can take quite a while. My current method of handling this is terrible, hence the other open issue; it just waits about a half second from when the ContractsLoaded GameEvent fires (it fires at the start of the loading process, not the end...). 

If these exceptions happen because they are being called before the window is loaded then switching to SingleOrDefault might be enough. It would just do nothing until the contracts are loaded.

The other possibility is that finding the right parameter by trying to directly match parameter objects doesn't work like I think it does. Contracts can be uniquely ID'd by their GUID number, but I couldn't think of anything that could reasonably be used to ID a parameter like that. Finding the right parameter by directly comparing objects (if (parameterReference1 == parameterReference2)) seemed to work when I tested it, but it might still have problems.
